type Subscription {
  triggerSubscript: Sub
}

type Query {
  _gql: String,
  me: User
  # @cacheControl(scope: PRIVATE)
}

type Mutation {
  UserCreate(data: UserInput): Boolean,
  UserLogin(email: String!, password: String!): String,
  Add(data: String): Boolean
}

input UserInput {
  first_name: String!,
  last_name: String!,
  email: String!,
  password: String!,
  provider: Int = 0,
  url_photo: String
}

type User 
# @cacheControl(maxAge: 240)
{
  id: Int,
  display_name: String,
  email: String,
  url_photo: String
}

type Sub {
  data: String,
  created: String
}